version: '3.8'

services:
  django-app:
    container_name: education_platform
    build: ./education_platform
    command: gunicorn education_platform.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./education_platform:/app
    ports:
      - "8000:8000"
    env_file:
     - ./env_variables/education_platform.env
    depends_on:
     - postgres_db

  flask-notifications:
    container_name: flask_notif
    build: ./notifications
    command: flask run --host=0.0.0.0
    restart: unless-stopped
    volumes:
        - ./notifications:/app
    ports:
        - "5000:5000"
    env_file:
        - ./env_variables/flask_notif.env
    depends_on:
        - notification_postgres_db
        - django-app

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "88:80"
    depends_on:
      - django-app
      - flask-notifications

  postgres_db:
    image: postgres
    restart: unless-stopped
    ports:
        - "5432:5432"
    env_file:
      - ./env_variables/postgres_db.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
  

  notification_postgres_db:
        image: postgres
        restart: unless-stopped
        ports:
            - "5433:5432"
        env_file:
          - ./env_variables/notifications_postgres_db.env
        volumes:
          - notification_postgres_db_data:/var/lib/postgresql/data


volumes:
  postgres_db_data:
  notification_postgres_db_data:
