name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push django image
      uses: docker/build-push-action@v5
      with:
        context: ./education_platform
        file: ./education_platform/Dockerfile
        tags: goldenjaden/edu_django:latest
        push: true

    - name: Build and push flask notifications image
      uses: docker/build-push-action@v5
      with:
        context: ./notifications
        file: ./notifications/Dockerfile
        tags: goldenjaden/edu_flask_messenger:latest
        push: true

    - name: Build and push flask messenger image
      uses: docker/build-push-action@v5
      with:
        context: ./messenger
        file: ./messenger/Dockerfile
        tags: goldenjaden/edu_flask_messenger:latest
        push: true
