name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push django image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:education_platform"
        file: "{context}:education_platform/Dockerfile"
        tags: goldenjaden/edu_django:latest
        push: true

    - name: Build and push flask notifications image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:notifications"
        file: "{context}:notifications/Dockerfile"
        tags: goldenjaden/edu_flask_messenger:latest
        push: true

    - name: Build and push flask messenger image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:messenger"
        file: "{context}:messenger/Dockerfile"
        tags: goldenjaden/edu_flask_messenger:latest
        push: true
